import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import LogOutBtn from "./LogOutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body>
      <div className="navbar"> 
        <Link href="/" className="logo">forum</Link> 
        <Link href="/list">Profile</Link> 
        <Link href="/write">Post</Link> 
        {
          session
            ? <span> {session.user.name} <LogOutBtn /> </span>
            : <LoginBtn></LoginBtn>
        }
      </div>  
        {children}
      </body>
    </html>
  );
}
